export const gameInstanceConstants = {
	playerTruncationSize: 5, // will not truncate if set to -1
	slowGameFpsThreshold: 15,
	serverNameMaxLength: 50,
	numGameInstancesPerRow: 4,
	serverListTypes: {
		friend: {
			key: "friends",
			value: "Friend",
		},
		public: {
			value: "Public",
		},
		Vip: {
			key: "private",
			value: "VIP",
		},
	},
	sortOrders: {
		descending: "Desc",
		ascending: "Asc",
	},
	defaultOptions: {
		sortOrder: "Desc",
		excludeFullGames: false,
	},
	resources: {
		ascending: "Action.Ascending",
		buyNowText: "Action.BuyNow",
		cancelAction: "Action.Cancel",
		cancelPrivateServerText: "Action.CancelPrivateServer",
		cancelServerText: "Message.CancelServerConfirmation",
		cancelText: "Label.Cancel",
		cantJoinPrivacySettingText: "Label.NoOneCanJoinServerDueToPrivacySettings",
		configureServerText: "Action.ConfigureServer",
		confirmCancelText: "Action.ConfirmCancel",
		confirmEnableFuturePaymentsText: "Label.ConfirmEnableFuturePayments",
		createPrivateServerPriceText: "Label.CreatePrivateServerFor",
		createPrivateServerText: "Action.CreatePrivateServer",
		createPrivateServerTitle: "Action.CreatePrivateServer",
		createServerFooterDescription: "Description.RecurringSubscriptionRenewal",
		createServerFooterText: "Label.FooterText",
		descending: "Action.Descending",
		doNotCancelText: "Action.DoNotCancel",
		freeGameText: "Label.Free",
		friendInServerLabel: "Label.FriendInServer",
		friendsServersTitle: "Heading.ServersMyFriendsAreIn",
		gameNameText: "Label.GameName",
		hideFullServers: "Label.ExcludeFullServers",
		inactiveServerText: "Label.Inactive",
		insufficientFunds: "Label.InsufficientFunds",
		joinServerText: "Label.ServerListJoin",
		loadMoreButtonText: "Action.LoadMore",
		loadServersError: "Message.LoadServersFailure",
		manyFriendsInServerLabel: "Label.ManyFriendsInThisServer",
		maxFreePrivateServersText: "Description.MaxFreePrivateServers",
		noServersFoundText: "Label.NoServersFound",
		numberOfPlayers: "Label.NumberOfPlayers",
		perMonthText: "Label.PerMonth",
		playerCountText: "Label.CurrentPlayerCount",
		privacySettingsText: "Label.PrivacySettings",
		privateServerHeader: "Heading.PrivateServers",
		privateServerLabel: "Label.PrivateServer",
		privateServerPlayWithOthers: "Label.PlayWithOthers",
		privateServerPrice: "Label.Price",
		privateServerRefreshText: "Action.Refresh",
		privateServersNotSupported: "Label.VipServersNotSupported",
		privateServerTooltip: "Label.PrivateServersAbout",
		publicServersTitle: "Heading.OtherServers",
		purchaseError: "Message.InternalErrorPurchaseError",
		renewalCanceledText: "Label.RenewalCanceled",
		renewPrivateServerTitle: "Label.RenewPrivateServer",
		renewServerListText: "Label.Renew",
		renewsMonthlyText: "Label.RenewsMonthlyCancelAnytime",
		renewSubscriptionError: "Message.RenewSubscriptionError",
		renewSubscriptionSuccess: "Message.RenewSubscriptionSuccess",
		seeAllPrivateServersText: "Label.SeeAllPrivateServers",
		serverCancellationSuccess: "Message.ServerCancellationSuccess",
		serverNameText: "Label.ServerName",
		serversText: "Label.Servers",
		shutdownServerError: "Message.ShutdownServerError",
		shutdownServerSuccess: "Message.ShutdownServerSuccess",
		shutdownServerText: "Label.ShutDownServer",
		slowGameWarning: "Label.SlowGame",
		startRenewingPrivateServerPrice: "Label.StartRenewingPrivateServerPrice",
		subscribeText: "Action.Subscribe",
		transactionFailedHeading: "Heading.TransactionFailed",
		twoFriendsInServerLabel: "Label.TwoFriendsInServer",
	},
};
